# Generated by Django 3.2.9 on 2021-11-28 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equitymasterapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityOwned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('average_purchase_price_mv', models.FloatField(default=0)),
                ('average_purchase_price_fifo', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('equity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_owned', to='equitymasterapp.equity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
