# Generated by Django 3.2.9 on 2021-11-28 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equitymasterapp', '0001_initial'),
        ('equityownedapp', '0002_auto_20211128_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityowned',
            name='equity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_owned', to='equitymasterapp.equity'),
        ),
        migrations.AlterField(
            model_name='equityowned',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
