# Generated by Django 3.2.9 on 2021-11-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equityownedapp', '0005_remove_equityowned_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityowned',
            name='average_purchase_price_fifo',
        ),
    ]
