# Generated by Django 3.2.9 on 2021-12-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equityownedapp', '0006_remove_equityowned_average_purchase_price_fifo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityowned',
            name='rate_of_return_fifo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='equityowned',
            name='rate_of_return_mv',
            field=models.FloatField(default=0),
        ),
    ]
