# Generated by Django 3.2.9 on 2021-12-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equityownedapp', '0007_auto_20211205_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityowned',
            name='rate_of_return_fifo',
        ),
        migrations.RemoveField(
            model_name='equityowned',
            name='rate_of_return_mv',
        ),
    ]
