# Generated by Django 3.2.9 on 2021-11-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='equitymaster/')),
            ],
        ),
    ]
