# Generated by Django 3.2.9 on 2021-11-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitymasterapp', '0002_alter_equity_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='market',
            field=models.CharField(choices=[('KSE', 'Korean Stock Exchange(KSE)'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'NewYork Stock Exchange(NYSE)')], max_length=20),
        ),
    ]
