# Generated by Django 3.2.9 on 2021-11-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitymasterapp', '0003_alter_equity_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='currency',
            field=models.CharField(choices=[('KRW', 'KRW(￦)'), ('USD', 'USD($)')], max_length=20),
        ),
    ]
