# Generated by Django 3.2.9 on 2021-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitymasterapp', '0004_alter_equity_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
