# Generated by Django 3.2.9 on 2021-12-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equitymasterapp', '0005_equity_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='current_price',
        ),
    ]
