# Generated by Django 3.2.9 on 2021-12-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_auto_20211206_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='ex_rate_usd_krw',
            new_name='mkt_ex_rate_usd_krw',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='capital_gain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='capital_gain_exchange_adjusted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rate_of_return',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rate_of_return_exchange_adjusted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_ex_rate_usd_krw',
            field=models.FloatField(null=True),
        ),
    ]
