# Generated by Django 3.2.9 on 2021-11-28 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equityownedapp', '0003_auto_20211128_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('transaction_fee', models.FloatField(default=0)),
                ('transaction_tax', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('equity_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='equityownedapp.equityowned')),
            ],
        ),
    ]
