# Generated by Django 3.2.9 on 2021-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitytransactionapp', '0003_alter_equitytransaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', '매수'), ('SELL', '매도'), ('DIVIDEND', '배당금'), ('SPLIT', '액면분할')], max_length=20),
        ),
    ]
