# Generated by Django 3.2.9 on 2021-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitytransactionapp', '0004_alter_equitytransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitytransaction',
            name='note',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
