# Generated by Django 3.2.9 on 2021-11-29 01:38

from django.db import migrations
import equitytransactionapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('equitytransactionapp', '0006_alter_equitytransaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitytransaction',
            name='quantity',
            field=equitytransactionapp.models.MinValueFloat(),
        ),
    ]
