# Generated by Django 3.2.9 on 2021-11-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitytransactionapp', '0009_alter_equitytransaction_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitytransaction',
            name='split_flag',
            field=models.BooleanField(default=False),
        ),
    ]
