# Generated by Django 3.2.9 on 2021-11-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitytransactionapp', '0012_alter_equitytransaction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitytransaction',
            name='note',
            field=models.CharField(default=' -', max_length=20, null=True),
        ),
    ]
